name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Checkout repo
      uses: actions/checkout@main
    - name: Download Mars.jar
      run: curl -o mars.jar https://github.com/dpetersanderson/MARS/releases/download/v.4.5.1/Mars4_5.jar
      working-directory: ./tests
    - name: Building and Running tests
      run:  ./test.sh
      working-directory: ./tests
      
